server:
  port: 8088

---
spring:
  profiles:
    active: local
    tomcat:
      max-active: 100
      max-wait: 10000
    include: datasource
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true

---
logging:
  level:
    org.hibernate.sql: debug







#  jpa:open-in-view: false # 이 설정은 "Open EntityManager in View" 패턴을 지원하기 위한 것으로, 요청의 시작부터 뷰 렌더링이 완료될 때까지 영속성 컨텍스트를 열어두어 지연로딩된 데이터를 뷰에서 액세스할 수 있게 합니다.
# 데이터베이스 쿼리가 뷰 렌더링 중에 수행될 수 있다는 것을 알려주는 것